### ISSUE TITLE
[Bug] No items added by this mod are craftable

### ISSUE THREAD

**Issue by charlesfire** [Lionmeow/AcceleratorThings#1]
As of Slime Rancher 2 0.5.1, none of the items added by this mod can be selected or crafted in the fabricator even after buying the blueprints in the ProntoMart.

**Comment by Lionmeow** [comment]
This is a bug with MelonLoader 0.6.3 and 0.6.4. Unfortunately, there is nothing that I can do to fix this until 0.6.5 releases, which will fix the issue. 

I'll keep the issue open until 0.6.5 releases for information. Use ML 0.6.2 or prior.

**Comment by Lionmeow** [comment]
0.6.5 fixed it, and now it's actually on 0.6.6. I'm late!
